// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFsplHdNLLso6JqCDWM2jcIOypGCz0HMA',
    appId: '1:789870460869:web:b87c55c006c6c7ada315ac',
    messagingSenderId: '789870460869',
    projectId: 'atelier-d-art',
    authDomain: 'atelier-d-art.firebaseapp.com',
    storageBucket: 'atelier-d-art.firebasestorage.app',
    measurementId: 'G-H5N585FZR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0Lfe02SHOXM9qFQAt8G6b6TOWAF36HZ8',
    appId: '1:789870460869:android:62bda5b82d43dfbca315ac',
    messagingSenderId: '789870460869',
    projectId: 'atelier-d-art',
    storageBucket: 'atelier-d-art.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCslD3DsCreRFW8PitTcFPFvLR6NcqVk5o',
    appId: '1:789870460869:ios:24397d68d21cb3b6a315ac',
    messagingSenderId: '789870460869',
    projectId: 'atelier-d-art',
    storageBucket: 'atelier-d-art.firebasestorage.app',
    iosBundleId: 'com.example.mainproject',
  );
}
